string = '''GIxrGOvgcFEPYvkIdinQxvELNmLOihKTawpZpwRStVgpaChBqVdPMjlVkiRiTyCwuzslJxPCHhQOLxCSpaHwrCOs
kErlFrnITQJQVKRllXxCLIDRGiTkhwAGHtgZMMlDMhuFzjcabfEPOQCPDqUrODXaTLAEOuxyGaFNOaVQDogGVlGB
oFqkYDpcVbZgBmIyYMKybLdeQURopXZPpYDkSqjoRoRYaOyKfduOGmErzDFXbEhKIquXNVvaWrYCYsGSMTbgWGyX
fBSzLliKPlIgTGOCQBcTBOrKzXMihRcSdjWpLnvTVyNgwmtTbnhIqtTkQCuESFvegkITtnriWUwIJLwtsPAYfYAC
XlmIwqBxAEiEvLihmnUnyJUrmFGvqoRXKMETKXAzYuKHNSfVDtVlDiKZFiaulyknnhgjpvWrRRffnAzMbLgnnSXN
EZbIkGCtAStnUTjmBRCLcvNMkykiIIUQHUlvzyuvdfdnUqSDLuhaKzFQEXSkIXcpsjCVHPONKkEoKluzanlLaoSB
RCdXyTsuOrtXvYFHyFhleGiWYAzrtbbvQxiDqDvFsZutmqsSvIGUpXKEoaBGNOMcIgjdJVJkMtSDrHgwIFgIVAGB
SAHhxhyreMpiNdeTiExcSwDlzuKxkGsezvrpYhPyXXWmkfdOXzYOfenrsNhOxycVpNlEVlIJUOpvpBvwPWGmPsNC
zKQHSjCDhVMpdaIfwnbkIhaqDxxuMDbalNTMIgpYDOepCTokPGQpCVYeEgmdYlVhyRUaESlQftMbFgshqcHLbUKN
gRAjouxrZoCfEtJdrWjanPjbXiIEkPWzjsByuAdrPELFrpujDUmdnSiiQpEOILWZXJNDFOkbuARJDUwEznToXzPi
StPPUfnYQBkfoHNASsGHrvCWIDbMDudpshPfBStgxVUNvfYzcvyoAKJNEXKEHBctzyslaWkGWHOVKseqdCyCwiVp
yZktoqHmLPQMXqFKoBkPyALLGPFAfjKgOqfbWhqyxQQkSYopkSbnLppRYwCHGTUjqmskRCxWiUCCCSTBfKQjdSpd
PtASKNtcZWGdMEWBLLhkEfDQVvMRvbaqybEtROWJQrdPTXJunkwMQuytZytqJSqQUlmcqtxOJfpHqDRfMquqjxLf
IiDoICjWfcksTygJGCMgPZGIKAWTFlMErYlkadxZqKmPIhuRBnRMhATWUvOdhlNHICpTOqPwpPbBWKrFfEKocJId
QbcanRHsxROjvmLWKGRAVZFZUIFkvBHKdYmKwABQmBUsiutHAMnbnAYFQHciRuBndMROCftFVAejJsINPrXZOJHz
oEMVZFdLuYbrdlFKoTVROFJQlAbMginyDhwqbFhKMUkwrXAuRXjiGWXiYeaVPDuitnmIZqgieBnEdDqxiYQNYfPB
vCnIBadREAJmGezKfxlljSgaoCLYSSWlIOkdiHbHHiWwmeLxasWjRlbjMfumQnWuSVYHLByeWomRjgPjaBjPhVqx
JjxfiTJmUhcNjOWSstgDNKyozzyShtKqKiFVNVrMziZFGyALEbiCcLZwNzHHosXJSHQYaSWzzycroDMZzsASOnoK
EFWpbpxZceAKOEafyJzjCMQQMhOWgDXnfXIalXHIVkhNySsXYReYfxyqvgqbQvXNizskzqaBHOMNDfDxOyJNbSCv
gmSDASzLPaMuYBbtHSapfvjfjmPdPRKCfbcaGnxLbhDIpJNoDaurfTFmBWtfNAfbGiiZxPnvebsrtfanNEMbBLFO
XhyVcKWUGVEFhYMigcHajRqJpIiFaAelVVwtsgGRRjtzvTlCBCWZowEWKZYkkxFMZIIWayOKCMaeBpUdNdcZmQnx
yHaVNhMRcPdnXXdsuzCrAhrkNHTvxddgjPiXgzDHmzfKtATpjQEkzxTEwbwsSatFznvyBwwTXVANPiuLtkzXORPO
IZomjbbuogFbwMfHROoueWEPLfPPpeOvFvmPCbRmRdWhoWjjYcReNsrsjiLBPTpKRWKbhFYSZIazLbFQZgQUFMPU
hYpoqvLrukKFEmwCYLXRzopuykbRwwHSkYWefeoDFiCtioRhfnYfqIqBCmHITSefyFyCvoUenoXQNivIbXXnDLzx
njSeahKPMGzMWWcHWUaXfOOXgXhUeQuPEySKQbWMoXTnuxtyqzFWqlYtXExRtkGdpHfLbgwXnqgqGuITzoWHEYLE
hYYSzWgLojTFKNkMoqmWleSqyTlSTIRoVWbElWdiUMVnIgeJhSPxAUjmXnIbYICIICehuGTpQUZQtjXrBpZShEUk
WftvSZFBMOuVMQAqPyEfHmyBCgZiUzAKnhHBYPqbjdoJGevWTziEzFUiNDfkzomtPwXKkEcGfuCwyAhZdimASMkg
ohVpKLJhMYOeMbuEzalzcPQvebLBMchjRfIOucgXeRhhpUwSwTGEFJAyfvJGRqsRNSKvNCICdusxXNnqmtMkDAk
sLFoBzUWXttSubByGGWiSNYtUueTTGnJIuqIeHqXbFDTuazTDNDyJyYHQjLhznDPMDEDKcJQSKHRCrRVxNpWzAPB
SXDhfxqNWpOELoQijOMTnuKrvUNatvQbTPvexBQIvXAytAPMNHJyFmdjqgzhxvlxQgvqyhwkaeBcEJWoAQfKKvbm
noBVQnDVUcisSfDcKtQWysksycLoqQdLdQXoUDLsHrVthOPZGYprztlYopRlAOqmPDndexPQDFsUXEixSzNIbcMg
UcWmemoDTcNjrbFxGlHAaFGtELRcdIrapPEdgLIqrjOXqqGqOBmouefQuaRDpCXTjajJVgcsOLUsekhcCuFdDuio
fhtDdQyoyQuFxEtSoguwICkBUxJHJeMhzJSnqNQjrjoACzZkKFYwIyTzbdkDWASkdBzZMfRCQzVvnHNktDBiVbwb
VloqKwLQVJrseqkIpeRCODnvFaCZzIAZVJnaJewjpASBGMZKYDKyGnCZkZuCXQeHZIgByyrsPEWDKccTIVLjNlyx
PGPgyMRWjwkXcMJnWZBLANMMLzyTZETyeHEMmatrhRyvWjzbHoeNBPmhbSoVCVSQqJADoehaDzYMGTrBimugisKC
goXVogngqMBgbRVFhTAmhFTGVMviNDdNaGNwwuOEhKXMukYYNwYOqxRIyWMBwdsCiSHGefvrBRhRLAoqhVyTvKYD
AYAMFxgAwhaORObVIvqqFLMRLUZjnTjvEynphruBepsZSKBSHtdqEvRPTrBOajYngRpNZbHBUWNjHEcAnkEPxLWh
VZbqCKcjSzZzWUKKCjPzPQJBspsbABmexfIQpHANnQtRNhjrsnxHTWxttYkYcFvcOnddQoitgfpQefmVsUVtIRcz
NqUBxmWzjrbowNuhVYwoAbVQuehKJzjHJHypYHbGrGpEzdcPdknNauVsaBiCspjjPgKkIiWddYOAAYgIJUsNZGdr
sZpGUeFiuNOrmEssVhLUdiHaUCbXNZVBdxlsACgWkSBqyvkDwgwslsLKKKUbYxIedOXbXFfGiAYhSJXQbomplLwU
wBTsgaIsTTuBsAbaxnUpFiaJHoooagWRKCRsOpSUFeNJBrRfoOiPfvBTXuzdaPUzPLVVeFNfYOHBPFzXNXHMXmSi
vnQjSYzgQWiPDXJgGMtqlpJNwmIdqiSUfTMZRTlrwduxvJyEHqJdgmhnPxZxuBPwyOLFKmavZzNnLFbisnuSxWHY
MwzowPxovztlqPrdEYYnazTdHPunVQBNkQUIJKRNpfcfhVslhQzQVKlzHcPfxwoMyAIqEJrUBUmjSnVpcWnsIBiv
uwNryHfmwVcXiIJslpLXqPyMmIgbQdxwcqVsmQDBKCRLePGLXagGKELvbmlKLelcasdYegiKPiAehvnMSIyfowZu
OGmgdlWVxcxiswlwUPtEsFUwSXPfzwthMykuFcevvkKdDQKUBWoGwqXiREmbFyCgzzhkNQipVLcxqfbUgTyYfqWM
HzCwcphsDTTmxmvBTfVrVXdpTXPwFyDkVWcLQjSyiIPlDWPuYdwyzOCCkQpDpZepLheJbCYQbrsKloaswSdzGgKT
RmfInYBQsNZpHQTaOZsDRxIDggVweMMsQPfbARlxJuORAPIAFNoMhhykllNALSKrGzErZcyDXuBicHaANpTqLITq
MnkEYsHSwwfoeVYKsSazEFgTrinvkJBKjuWAxKsBlZjnHfwHHxoLyJtQFVeseWSoyjHOJguSllXdjsgGTcLKGgji
grtFrvwyiHYlHMATFMJyFnlWeIUlHeHuDKwSrgzvhBYZyUeEoFyhXBEJUUpxXzscMqgVSeFgMguYcXmdwppjmSVR
FNqbcbdYxQplfPlAwvNRkwxaKiauzJBGjmGRcJliJtOEviIfSzQsVkCksIDVCqWcagnJOIxsLLnZKgvqoxsFzzzs
AcvemwsUucEokaTGxVBrYeDrYjYNbezMbVEkdkzEYgrNpUavdiMhPTGYXCxYQFyabtjlfzhJyQwsDtmgjaZZdyjy
cbRoPVbTaqESbBKIQQeyKTozpSYNGYLXfqOOZbwJLNPERRczyFyUQziQmkrjGWVzleLlAVZUzVgboNtXQRwesMUl
jmjwQmpgvonblxteRZVDSGkBNhJlfDBQnTGPvgmoReXixfDRCHYkBRSBPZqlHSKteFYqcCxoLHfDtRTqEhtBYtOd
bCPWRnEqfmtBiOoNmhAyTKWWUXPVZyuYpilfTZJjQiowONbjQRtYvWFSVRbdQGuVTmMEuIYcYOPjTuiJiUhZtXdQ
EeIkwMUHESHbRzYTPGZfAuynVFFNrUMwOHuWEpUbZUfeUKVhTdbOsvBTROZiNUSksOLXkTqacopacEUCTqioknvL
EEKnKbjYlHLSzLRtqpvcnxNIpYSzomUSyZmmYeHluFOFNGNQbGDvtkqZVMkQUupqCCyHVGGwPcnQzWhKGjiUUldM
JxLoHdyvJAidSMXfvOPExKEcmybcnoQDqEufobOKutKXNkwjSLdkoWOwlbqyNGUULbjHjFizPLJGBrMylgVPgWOJ
oXUqrfGnArbVnygrzgMqBOhSNuUdEYTUCGQBAiSDRrvUaSjGWZJueQuQUriOQTpPngqqoRmfOpzevNTfOFXKGIEb
qkWLbdijTTSDimqCdrqSTCNUFPKvFBArXGMFCenfJgVZiWaZwfTgIeMCwtyMWzHUSmJEBKSWWEYivmkwANzvJDfH
zqYbqPicJuaEhJLstitQFXvMvIvUmJKblJNbxKsRDWhtShBjXYncqwysZJUdSKrjUuTvcEHwkpeUQJMOPXwcniwO
mULxzCphLNeyyLTPWBIicaEKHZgosOHZyADyQxrwflRiMXmxeHMncAmJVKbgKNsjOQIIWRmyBqiykzKLsmbBtqBq
HyMgVRNofSxgiaUirerfhrjvZOhqsmBeSnHGtBgaMLoYgBcaladjzBUrqlHpYyVRWugXHntVWkyUNsUbAvNbGNvf
BgTMkhPPKtYvmMgqQkCeGfQMFFVYJWqiPLlLSdiVsgizxdydwFeVJNaSbTLZgmmOCDkyhvRsKnhnHQCkdKZitEQY
nyuPHkaNPLDDAfCPYbjWhIwoaZtHgGOkpMzraxhuabOOqAjBRDkktDZAPmJcQeHsrgTehLkawAwLUZNUHqzbdTDU
BeqdciERzzLfKHqHxKEaqEjYwprZLhRBdcrQjCAIzFJljbFDsgzbUyziHhojKAgARmhJmLqStnDmqkQpqwItAWRG
hXRZlzrbLxCboAqgjInolJouBzDdsABPnYxJthpXwDKAulIksAuyxacifxscWMpAIFeRTKhGmNXpHrGiofIBRSOj
ITDJfskjytwAaPGzJAYCLImistwFbDoNYEOkwTBuDDIeGuuNCqZnfiaKyvxeSOwLbBlfIJeBRxyQkvdRirhkAHgT
QoSAHYiZoPfgkNaCUWfXobCWDIhoCcNLqLjMkDeOyqPnLqtZiznycIHhHmMUTLxuFRIzUEfwjhRULqDPRNYdpbOK
nOUEmLuKAURDAmrxRmVemhfURDRBdVLdmBHfrFzZpmYMiZfwQpueqjAEacNibcjujIknxQNIokArRiZKLMMiTLqG
gzyqVhWQUaBPLPtnMdDKJPiehNUGtWagxGCribQchZLrZFryEKHCRpbGvAnMEgWdgIwWEnsrobGFlizTAIAjmsaz
PQqkAmRBDXoKRAqZibPgTNgYbXFpDseQtMGkfhTghVSpzxPlIxvgNCxEddSdjEPdgRJpHGCmMUecXgKNWBQvADNF
JNpQCcORJadcJfYgGrpLuBHrhlVDoXiUeOfGETNEfiXEJUDdaGxEaYKsPuVodnVAQyysAcvrQQHMfTAfnISsVIGd
ZpbDeoOEXDRKOrPMNdipqekwhbVLlCODbJYxJpSHaraabZwKQzmFsqdziRjaSqvMifPHaNBoqFcWCprmYMxvLDIj
HpiZaCHjxiPhGgaatBhPOosslAyLxVJnzCzuCXDYJyZPmeMMEHHrolEeOIhzJbSoRQaGmXuGrctDgggQwjNzuKmN
oHMqJvNdXBjeHnPJVrTjqKZOKxXMUIHkDEPImOkDqGtPmlrzuVrjgNRUPlSoUswpEAqDXOcJuUkDZnnVyjqYSokE
ZTUkOAkKTNVvZUMvCJqmNrIhKXngJANPBrJtWgxaiphMoXekheOYcOwvtGGPIkZnyhFRzzioefjMufJYknsgjQTT
XeziKoDymQIkrtllLFXOgpwAaWEFDWNCUdGeozcQrbwTmyGKXTKQGfwoiXQhegweuHzyPdAsRfnnAflOYRWNBBWr
eDqpeHznjOoCePwXXzoSCZxUPiTmdtdaEXjqTXCgVNdHMTwYGXqLgbqGBdJDZySDUedrVcdmPWPjtRYGTfdGyDby
bUssXJRHPtCxhQWTEjRUaVNEMPVDnWsXLiqTUIgIvSUEYdyQLEhfTXieQNqyQxopNDLCFOwTRxtvuUdPMbUCYNlA
ZOxHpLEKqgvxMuBsDyynpdCqlLSpSQCeWBIaIyFmGDYFSYawQYTDyttNhgfyrwPQyPcZEgynvkZDExwlGZKTIDOA
aOfybdcIFOSkxVsZVKfozFBdgeyoWmouFcUMUPrEFUZbrBxgBXKVdQUiRTmxhOiPtnZUsAbClJfcxtGksEVljqeC
tPOQvWPtAMyXTbrpSXmtKmEiWMyXnkmVIKdNLiaYIoeRMkAtymYunTyqOZExosILJiUNivMKfeIQAaqjBCgKLyXC
qCcXCSQJBAzrSlzAVMmiPISLvrRESKoPtyQwnQwhLnbPbYvOkIWxguPtVqLaIcUOpUIRdQTnWAOwwlrrooBLNDka
tBCMJhmXPKyBRmfuNMcFzrRYxITSKDKqfSZZGNYgmQBYIjfUEHfrAjosVzNaeBoXAilKwzhQdNHlkONTHbMeIQMY
EmWVXuaiBkqDxKYgEqKaWqBmpjAclFbEPGRJfXDHZpBpWsULCvWDwTfKsbmobbPOKwIcOxRKyXHSPPNdSnLqMnRb
FsihjcsmdzrtUkgiymBPqmEykxLbANvuhqTzIBgSsdMSkfFtxmkuZKgoEGvEupclhnDymixYEOHuHfePxdAdYmCP
zDnTTYOYlRYyjgcLWqPNVhYKdzcFkTTCacANCiUPiiIyNgtflgnJvOAFRjswaSrmGXhwyfuVmIVHeGHDSHBHzkfq
dPexLvWCqmrUVRsWYdNOztOxnswXmvmauCuIcLqcSDbmAyzvBZsEMxvxZmCkyIxFSjWmdrCKEQCXnYEMTkiywUUc
kuVEthxmUPowEthebcyNoCRdnzORQUYUJeLjSiuXXcxJAwgoSDkDLOaNPPrXyKMYfKTqaqxqvpTJOXiGEtWqaKSH
IRLxzHpvNRsdnvWnckRdKnAWemVQZbyLnAUrauljKSklQJjzvRJzPxPGAdlRUdQdFCjXuKOEAxnOsHdGNKZSepju
DRwTfPuDtXjnMTaTPyKMpzxOXSuVqrFLixOunPFxcCNDHWstPEozGublYKqZeEZErabFzGgapVwNvxrLubRYYIDt
jmishMdfUKUqHUGBclwCjJssVuEZUaijHPLuoNMbKdXWGFJUYtKBWGkRXozLSROIPIexqbREmTuFvIJKftVjrCvG
xaYDTxHgXyNWwdnwvxGeIAhBotMaFJHUonftrjcHGsZmBmQBvriodNrXoezEcpohljjucdnrNSGmJxVXSaXRzGou
bGCysuBQWTatFvBFlgKkuiqZgSHjnYxMHQNnrviwfKqptuuuElBLIdgsOwruAJxzIgdKuzoELaauQOYUVtaBXNkv
nqfBiwgwuSZQvnyRYrZpJfYcZiJtKwjqNQfVbDzKnXXEDzcFARrXsfombiwACCYOteLJOgmKMhJtBLGzLliUDvFJ
EvdeyVvOirUJZGUUNGosaZYwlRSJwqADgVcOxEMbwTKIdWtIIiMAGjOldREOUGiDjJLAlfeGPIqrUYbpeYTfPGIA
EORDGyGhvQyNkVKOIhNJQUYtxaQdKHETiHJppzdxKyltdwFXFhvIXMLULAvlYcUYyEhchqhSCnfsHHGtTdiTSOha
ghlVXutxCvYLrDRMUSuTaSeocGloVSncWEfIvXPEqpoQEXGCdWhSZaIVfWhAZKbFrhGMCBBriBizLilsvIZJKuvs
YPhkQIqHMDqTpBiFpJmHxGCUpFvYrwhLRjJLSrPFFoZLxptJcDxOpHvWrZRPHGrlpsqwXSEkmGwFgVdyiVvnGEnM
HInrxUqRMNJHsmoEofpzSHLfnAtHXMgZfdzaHYZkLCeuBvSHMGYodjuCcaagUUaUVEtYjxLKzSLJybygvzMJBRFv
RKqBaEkPpaNsaDefOaKGbCavLHYYShvwHySmlNZeLfPoHeKUQjPMlKVmEJpOIdbfywARtorGdRCHAZUDvHGUhIqR
DsivXszPzUkDCVRFAMCChhPMqizLqlcVdSSCVwXthAfSljZgNoABEWAmBOhnDFUSnyEPhURHVfEIEiGdTjyDcPiB
wnWSYEawwxptimAngiJbTdoNScQkuqpzHTGmOQdalrUfAoFGBuzpAESrleuFbJCwODgtJCNCcuSISIvBrsMIaqUs
ECxdnNZQJVPomSLBTgcPTsatdjzwyDnatPQnbpxcTVPVesSgioCYMFNWlOJoXfEaCpebWzJxpztaZHgYqjjQeONz'''

def isUpper(letter):
    return (ord(letter) <= 90 and ord(letter) >= 65)

def isLower(letter):
    return (ord(letter) <= 122 and ord(letter) >= 97)

def testMatch(string):
    if any([isUpper(string[0]),isUpper(string[4]),isUpper(string[8]),
         isLower(string[1]), isLower(string[2]), isLower(string[3]), 
         isLower(string[5]), isLower(string[6]), isLower(string[7])]):
       return False
    return True

string = string.replace("\n", "")
tmp = ["A"] * 9

for letter in string:
    tmp.pop(0)
    tmp.append(letter)
    if testMatch(tmp):
        print(tmp[4], end = "")

# tmp[4].replace = 
